<testsuite name="frontend.login.login.Login" tests="2" errors="0" failures="2" skipped="0" time="5.820909" timestamp="2023-08-21T13:36:53.690123" hostname="LTP-ISP-003303"><testcase classname="frontend.login.login.Login" name="Login with valid credential" status="failed" time="3.138419"><failure type="NoneType" message="None">
<![CDATA[
Failing step: When user enters the username ... undefined in 0.000s
Location: tests/frontend/login/login.feature:12
None]]>
</failure><system-out>
<![CDATA[
@scenario.begin

  @tcId001
  Scenario: Login with valid credential
    Given user go to login page ... passed in 3.138s
    When user enters the username ... undefined in 0.000s
    And user enters the password ... undefined in 0.000s
    And user click login button ... undefined in 0.000s
    Then user should be navigated to the dashboard ... undefined in 0.000s

@scenario.end
--------------------------------------------------------------------------------
]]>
</system-out></testcase><testcase classname="frontend.login.login.Login" name="Login with invalid credential" status="failed" time="2.68249"><failure type="NoneType" message="None">
<![CDATA[
Failing step: When user enters the invalid username ... undefined in 0.000s
Location: tests/frontend/login/login.feature:19
None]]>
</failure><system-out>
<![CDATA[
@scenario.begin

  @tcId002
  Scenario: Login with invalid credential
    Given user go to login page ... passed in 2.682s
    When user enters the invalid username ... undefined in 0.000s
    And user enters the invalid password ... undefined in 0.000s
    And user click login button ... undefined in 0.000s
    Then user will get the error message ... undefined in 0.000s

@scenario.end
--------------------------------------------------------------------------------
]]>
</system-out></testcase></testsuite>